mysite/blog/urls.py
from django.core.exceptions import ViewDoesNotExist
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("api/", include("blog_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from email.policy import default
from enum import unique
from pyexpat import model
from unittest.util import _MAX_LENGTH
from django.conf.global_settings import SESSION_CACHE_ALIAS
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title
 
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
            ]
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Комментарий от пользователя "{self.name}" on {self.post}'

# Create your models here.

mysite/blog/forms.py
from django import forms
from .models import Comment
from django_summernote.widgets import SummernoteWidget


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='Имя')
    email = forms.EmailField(label='E-mail')
    to = forms.EmailField(label='Кому (E-mail)')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Комментарий')


class CommentForm(forms.ModelForm):
    body = forms.CharField(required=True,
                           widget=SummernoteWidget())

    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from logging import config
from django.shortcuts import render, get_object_or_404
from django.utils.ipv6 import is_valid_ipv6_address
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    all_posts = Post.published.all()

    tag = None
    filtered_posts = all_posts  # Используем другое имя для переменной
    
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        filtered_posts = filtered_posts.filter(tags__in=[tag])

    # Постраничная разбивка с 3 постами на страницу
    paginator = Paginator(filtered_posts, 7)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Если page_number не целое число, то
        # выдать первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если page_number находится вне диапазона, то
        # выдать последнюю страницу
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'tag': tag})

def post_detail(request, year, month, day, post):
    try:
        # Приведем значения к целым числам
        year, month, day = int(year), int(month), int(day)
        post = get_object_or_404(Post,
                                status=Post.Status.PUBLISHED,
                                slug=post,
                                publish__year=year,
                                publish__month=month,
                                publish__day=day)
    except ValueError:
        # Обработка ошибки, если значения года, месяца или дня не являются целыми числами
        raise Http404("Invalid date format")
    # Список активных комментариев к этому посту
    comments = post.comments.filter(active=True)
    # Форма для комментирования пользователями
    form = CommentForm()
    # Список схожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                    'comments': comments,
                                                    'form': form,
                                                    'similar_posts': similar_posts})

def post_share(request, post_id):
    # Извлечь пост по идентификатору id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    sent = False

    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} рекомендует вам прочитать: " \
                      f"{post.title}"
            message = f"Читать пост \'{post.title}\' с {post_url}\n\n" \
                      f"Комментарий от отправителя \"{cd['name']}\" ({cd['email']}): {cd['comments']}"
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
            # ... отправить электронное письмо
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body', config='russian')
            search_query = SearchQuery(query, config='russian')
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


# Create your views here.

mysite/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Ваш комментарий был добавлен.</h2>
        <p class='p-comments'><a href="{{ post.get_absolute_url }}">Назад к посту</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

mysite/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load user_extras %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Опубликовано {{ post.publish }} | Автор: {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Отправить этот пост
        </a>
    </p>
    <a href="{% url 'blog:post_list' %}">
        Вернуться назад
    </a>
    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Ещё нет похожих постов
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2 class="h2-comments">
            {{ total_comments }} {{ total_comments|ru_plural:"коментарий,комментария,комментариев" }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} | {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|safe }}
        </div>
    {% empty %}
        <p class='p-comments'>Комментариев нет.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
<div id='main'>
    {% block content %}
        <h1>My Blog</h1>

        {% if tag %}
            <h2>Посты с тегом "{{ tag.name }}"</h2>
        {% endif %}

        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
            </h2>
            <p class="tags">
                Теги:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">
                Опубликовано {{ post.publish }} | Автор: {{ post.author }}
            </p>
            {{ post.body|markdown|truncatewords_html:30|safe }}
        {% endfor %}
        {% include "pagination.html" with page=posts %}
    {% endblock %}
</div>

mysite/templates/blog/post/search.html
{% extends "blog/base.html" %} {% load blog_tags %}

{% block title %}Поиск{% endblock %}

{% block content %} {% if query %}
    <h1>
        Посты, содержащие "{{ query }}"
    </h1>
    <h3>
        {% with results.count as total_results %}
            Найден {{ total_results }} результат{{ total_results|pluralize }} {% endwith %}
    </h3>
    {% for post in results %}
        <h4>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}
            </a>
        </h4>
        {{ post.body|markdown|truncatewords_html:12 }} {% empty %}
        <p>Нет результатов по вашему запросу.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Поиск снова</a></p> {% else %}
    <h1>
        Поиск постов
    </h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Поиск">
    </form>
{% endif %} {% endblock %}

mysite/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлен</h1>
        <p>
            Пост "{{ post.title }}" был успешно отправлен на почту
            {{ form.cleaned_data.to }}.
        </p>
        <a href="{% url 'blog:post_list' %}">
            Вернуться назад
        </a>
    {% else %}
        <h1>Поделиться "{{ post.title }}" на e-mail</h1>
        <a href="{% url 'blog:post_list' %}">
            Вернуться назад
        </a>
        <div class="container">
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Отправить">
            </form>
        </div>
    {% endif %}
{% endblock %}